/**
 * VoiceDesk Anchor program — integration tests.
 *
 * Day 2 will expand these into full coverage of every instruction.
 * Day 1 ships the smoke-test happy path: create_business succeeds.
 *
 * Run: anchor test
 */

import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import { PublicKey, Keypair, LAMPORTS_PER_SOL, SystemProgram } from "@solana/web3.js";
import { assert } from "chai";

// IDL types are auto-generated by `anchor build` into target/types/voicedesk.ts.
// Until the first build runs, this import will fail — that's expected.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const idl = require("../target/idl/voicedesk.json");

describe("voicedesk", () => {
  // ─── Provider / program setup ────────────────────────────────
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  // After first `anchor build`, the program ID in lib.rs and Anchor.toml is
  // updated to the keypair-derived ID. We read it from the IDL metadata.
  const programId = new PublicKey(idl.address ?? idl.metadata?.address);
  const program = new anchor.Program(idl as any, provider) as Program<any>;

  // ─── Helpers ─────────────────────────────────────────────────
  const VERTICAL_HOTEL = { hotel: {} }; // Anchor enum encoding
  const NAME = "Hotel Polonia";
  const DEFAULT_DEPOSIT = new anchor.BN(50_000_000); // 50 USDC (6 decimals)
  const CANCELLATION_HOURS = 24;

  async function airdrop(pubkey: PublicKey, sol: number) {
    const sig = await provider.connection.requestAirdrop(
      pubkey,
      sol * LAMPORTS_PER_SOL
    );
    await provider.connection.confirmTransaction(sig, "confirmed");
  }

  function deriveBusinessPda(owner: PublicKey): [PublicKey, number] {
    return PublicKey.findProgramAddressSync(
      [Buffer.from("business"), owner.toBuffer()],
      programId
    );
  }

  // ─── Tests ───────────────────────────────────────────────────

  it("create_business — happy path", async () => {
    const owner = Keypair.generate();
    await airdrop(owner.publicKey, 2);

    const [businessPda] = deriveBusinessPda(owner.publicKey);

    await program.methods
      .createBusiness(VERTICAL_HOTEL as any, NAME, DEFAULT_DEPOSIT, CANCELLATION_HOURS)
      .accounts({
        business: businessPda,
        owner: owner.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([owner])
      .rpc();

    const business = await (program.account as any).business.fetch(businessPda);
    assert.equal(business.name, NAME);
    assert.equal(business.cancellationHours, CANCELLATION_HOURS);
    assert.ok(business.defaultDepositAmount.eq(DEFAULT_DEPOSIT));
    assert.deepEqual(business.owner.toBase58(), owner.publicKey.toBase58());
  });

  it("create_business — rejects empty name", async () => {
    const owner = Keypair.generate();
    await airdrop(owner.publicKey, 2);

    const [businessPda] = deriveBusinessPda(owner.publicKey);

    try {
      await program.methods
        .createBusiness(VERTICAL_HOTEL as any, "", DEFAULT_DEPOSIT, CANCELLATION_HOURS)
        .accounts({
          business: businessPda,
          owner: owner.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([owner])
        .rpc();
      assert.fail("expected InvalidBusinessName");
    } catch (e: any) {
      assert.include(e.toString(), "InvalidBusinessName");
    }
  });

  it("create_business — rejects zero deposit", async () => {
    const owner = Keypair.generate();
    await airdrop(owner.publicKey, 2);

    const [businessPda] = deriveBusinessPda(owner.publicKey);

    try {
      await program.methods
        .createBusiness(VERTICAL_HOTEL as any, NAME, new anchor.BN(0), CANCELLATION_HOURS)
        .accounts({
          business: businessPda,
          owner: owner.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([owner])
        .rpc();
      assert.fail("expected InvalidDepositAmount");
    } catch (e: any) {
      assert.include(e.toString(), "InvalidDepositAmount");
    }
  });

  it("create_business — rejects out-of-range cancellation policy", async () => {
    const owner = Keypair.generate();
    await airdrop(owner.publicKey, 2);

    const [businessPda] = deriveBusinessPda(owner.publicKey);

    try {
      await program.methods
        .createBusiness(VERTICAL_HOTEL as any, NAME, DEFAULT_DEPOSIT, 0) // 0 hours
        .accounts({
          business: businessPda,
          owner: owner.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([owner])
        .rpc();
      assert.fail("expected InvalidCancellationPolicy");
    } catch (e: any) {
      assert.include(e.toString(), "InvalidCancellationPolicy");
    }
  });

  // ─── TODO Day 2: full booking lifecycle tests ────────────────
  // - create_booking_intent (happy path + invalid timestamps)
  // - lock_deposit (transfers USDC, status → Confirmed)
  // - confirm_attendance (full refund)
  // - release_partial (50/50 split)
  // - claim_full (no-show after grace, 95/5 split)
  // - customer_cancel (full refund vs late cancel)
  // - reverts: wrong signer, double-finalize, etc.
});
