/**
 * VoiceDesk Anchor program — full integration tests.
 *
 * Coverage:
 *   1. create_business — happy + 3 reverts
 *   2. create_booking_intent — happy + invalid timestamps
 *   3. lock_deposit — USDC moves into escrow, status → Confirmed
 *   4. confirm_attendance — full refund customer
 *   5. release_partial — basis-points split (e.g. 50/50)
 *   6. claim_full — reverts before grace, succeeds (skipped — needs time-travel)
 *   7. customer_cancel — full refund + late-cancel 50/50
 *   8. Auth reverts — wrong customer / wrong owner
 *
 * Run: anchor test
 *
 * Note: time-elapsed tests (claim_full happy path) require advancing the
 * Solana clock, which `anchor test` does not support out of the box.
 * They are marked `it.skip` and should be migrated to bankrun in Phase 2.
 */

import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import {
  PublicKey,
  Keypair,
  LAMPORTS_PER_SOL,
  SystemProgram,
  Transaction,
  sendAndConfirmTransaction,
} from "@solana/web3.js";
import {
  TOKEN_PROGRAM_ID,
  createMint,
  getOrCreateAssociatedTokenAccount,
  mintTo,
  getAccount,
  getAssociatedTokenAddress,
  createAssociatedTokenAccountInstruction,
} from "@solana/spl-token";
import { assert } from "chai";
import * as crypto from "crypto";

// IDL is generated by `anchor build` into target/idl/voicedesk.json.
// Until first build runs this require() will fail — that's expected.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const idl = require("../target/idl/voicedesk.json");

describe("voicedesk", () => {
  // ─── Provider / program ──────────────────────────────────────
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);
  const programId = new PublicKey(idl.address ?? idl.metadata?.address);
  const program = new anchor.Program(idl as any, provider) as Program<any>;

  // Provider wallet acts as USDC mint authority + payer for ATAs.
  // Cast to any because Wallet type doesn't expose the underlying Keypair publicly.
  const payerKp = ((provider.wallet as any).payer ?? (provider.wallet as any).keypair) as Keypair;

  // ─── Constants ───────────────────────────────────────────────
  const VERTICAL_HOTEL = { hotel: {} };
  const NAME = "Hotel Polonia";
  const DEFAULT_DEPOSIT = new anchor.BN(50_000_000); // 50 USDC (6 decimals)
  const CANCELLATION_HOURS = 24;
  const ESCROW_SEED = "escrow";
  const BOOKING_SEED = "booking";
  const BUSINESS_SEED = "business";

  // Shared USDC mint (created once)
  let usdcMint: PublicKey;

  // ─── Helpers ─────────────────────────────────────────────────
  async function airdrop(pubkey: PublicKey, sol: number) {
    const sig = await provider.connection.requestAirdrop(pubkey, sol * LAMPORTS_PER_SOL);
    await provider.connection.confirmTransaction(sig, "confirmed");
  }

  function deriveBusinessPda(owner: PublicKey): [PublicKey, number] {
    return PublicKey.findProgramAddressSync(
      [Buffer.from(BUSINESS_SEED), owner.toBuffer()],
      programId
    );
  }

  function deriveBookingPda(bookingId: Buffer): [PublicKey, number] {
    return PublicKey.findProgramAddressSync(
      [Buffer.from(BOOKING_SEED), bookingId],
      programId
    );
  }

  function deriveEscrowAuthority(bookingId: Buffer): [PublicKey, number] {
    return PublicKey.findProgramAddressSync(
      [Buffer.from(ESCROW_SEED), bookingId],
      programId
    );
  }

  function randomBookingId(): Buffer {
    return crypto.randomBytes(32);
  }

  async function createUsdcAta(owner: PublicKey, allowOffCurve = false): Promise<PublicKey> {
    const ata = await getAssociatedTokenAddress(usdcMint, owner, allowOffCurve);
    const ix = createAssociatedTokenAccountInstruction(payerKp.publicKey, ata, owner, usdcMint);
    const tx = new Transaction().add(ix);
    await sendAndConfirmTransaction(provider.connection, tx, [payerKp]);
    return ata;
  }

  async function setupCustomerWithUsdc(amount: number) {
    const customer = Keypair.generate();
    await airdrop(customer.publicKey, 2);
    const ata = await getOrCreateAssociatedTokenAccount(
      provider.connection,
      payerKp,
      usdcMint,
      customer.publicKey
    );
    await mintTo(provider.connection, payerKp, usdcMint, ata.address, payerKp, amount);
    return { customer, customerAta: ata.address };
  }

  async function createBusiness(
    owner: Keypair,
    cancellationHours = CANCELLATION_HOURS
  ): Promise<{ businessPda: PublicKey; ownerAta: PublicKey }> {
    await airdrop(owner.publicKey, 2);
    const [businessPda] = deriveBusinessPda(owner.publicKey);
    await program.methods
      .createBusiness(VERTICAL_HOTEL as any, NAME, DEFAULT_DEPOSIT, cancellationHours)
      .accounts({
        business: businessPda,
        owner: owner.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([owner])
      .rpc();
    const ownerAta = await getOrCreateAssociatedTokenAccount(
      provider.connection,
      payerKp,
      usdcMint,
      owner.publicKey
    );
    return { businessPda, ownerAta: ownerAta.address };
  }

  async function createBookingIntent(args: {
    bookingId: Buffer;
    business: PublicKey;
    customer: PublicKey;
    depositAmount: anchor.BN;
    serviceStart: anchor.BN;
    serviceEnd: anchor.BN;
    payer: Keypair;
  }) {
    const [bookingPda] = deriveBookingPda(args.bookingId);
    await program.methods
      .createBookingIntent(
        Array.from(args.bookingId),
        args.depositAmount,
        args.serviceStart,
        args.serviceEnd
      )
      .accounts({
        booking: bookingPda,
        business: args.business,
        customer: args.customer,
        payer: args.payer.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([args.payer])
      .rpc();
    return bookingPda;
  }

  async function lockDeposit(args: {
    bookingId: Buffer;
    customer: Keypair;
    customerAta: PublicKey;
  }) {
    const [bookingPda] = deriveBookingPda(args.bookingId);
    const [escrowAuthority] = deriveEscrowAuthority(args.bookingId);
    const escrowAta = await createUsdcAta(escrowAuthority, true);

    await program.methods
      .lockDeposit()
      .accounts({
        booking: bookingPda,
        customer: args.customer.publicKey,
        customerTokenAccount: args.customerAta,
        escrowTokenAccount: escrowAta,
        escrowAuthority,
        usdcMint,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .signers([args.customer])
      .rpc();

    return { bookingPda, escrowAuthority, escrowAta };
  }

  // ─── One-time setup ──────────────────────────────────────────
  before(async () => {
    usdcMint = await createMint(
      provider.connection,
      payerKp,
      payerKp.publicKey, // mint authority
      null, // freeze authority
      6 // USDC has 6 decimals
    );
  });

  // ─────────────────────────────────────────────────────────────
  //  1. create_business
  // ─────────────────────────────────────────────────────────────
  describe("create_business", () => {
    it("happy path", async () => {
      const owner = Keypair.generate();
      const { businessPda } = await createBusiness(owner);
      const business = await (program.account as any).business.fetch(businessPda);
      assert.equal(business.name, NAME);
      assert.equal(business.cancellationHours, CANCELLATION_HOURS);
      assert.ok(business.defaultDepositAmount.eq(DEFAULT_DEPOSIT));
      assert.equal(business.owner.toBase58(), owner.publicKey.toBase58());
    });

    it("rejects empty name", async () => {
      const owner = Keypair.generate();
      await airdrop(owner.publicKey, 2);
      const [businessPda] = deriveBusinessPda(owner.publicKey);
      try {
        await program.methods
          .createBusiness(VERTICAL_HOTEL as any, "", DEFAULT_DEPOSIT, CANCELLATION_HOURS)
          .accounts({
            business: businessPda,
            owner: owner.publicKey,
            systemProgram: SystemProgram.programId,
          })
          .signers([owner])
          .rpc();
        assert.fail("expected InvalidBusinessName");
      } catch (e: any) {
        assert.include(e.toString(), "InvalidBusinessName");
      }
    });

    it("rejects zero deposit", async () => {
      const owner = Keypair.generate();
      await airdrop(owner.publicKey, 2);
      const [businessPda] = deriveBusinessPda(owner.publicKey);
      try {
        await program.methods
          .createBusiness(VERTICAL_HOTEL as any, NAME, new anchor.BN(0), CANCELLATION_HOURS)
          .accounts({
            business: businessPda,
            owner: owner.publicKey,
            systemProgram: SystemProgram.programId,
          })
          .signers([owner])
          .rpc();
        assert.fail("expected InvalidDepositAmount");
      } catch (e: any) {
        assert.include(e.toString(), "InvalidDepositAmount");
      }
    });

    it("rejects out-of-range cancellation policy", async () => {
      const owner = Keypair.generate();
      await airdrop(owner.publicKey, 2);
      const [businessPda] = deriveBusinessPda(owner.publicKey);
      try {
        await program.methods
          .createBusiness(VERTICAL_HOTEL as any, NAME, DEFAULT_DEPOSIT, 0)
          .accounts({
            business: businessPda,
            owner: owner.publicKey,
            systemProgram: SystemProgram.programId,
          })
          .signers([owner])
          .rpc();
        assert.fail("expected InvalidCancellationPolicy");
      } catch (e: any) {
        assert.include(e.toString(), "InvalidCancellationPolicy");
      }
    });
  });

  // ─────────────────────────────────────────────────────────────
  //  2. create_booking_intent
  // ─────────────────────────────────────────────────────────────
  describe("create_booking_intent", () => {
    it("happy path", async () => {
      const owner = Keypair.generate();
      const { businessPda } = await createBusiness(owner);
      const customer = Keypair.generate();
      const bookingId = randomBookingId();
      const now = Math.floor(Date.now() / 1000);

      const bookingPda = await createBookingIntent({
        bookingId,
        business: businessPda,
        customer: customer.publicKey,
        depositAmount: DEFAULT_DEPOSIT,
        serviceStart: new anchor.BN(now + 3600),
        serviceEnd: new anchor.BN(now + 7200),
        payer: owner,
      });

      const booking = await (program.account as any).booking.fetch(bookingPda);
      assert.deepEqual(booking.bookingId, Array.from(bookingId));
      assert.equal(booking.business.toBase58(), businessPda.toBase58());
      assert.equal(booking.customer.toBase58(), customer.publicKey.toBase58());
      assert.ok(booking.depositAmount.eq(DEFAULT_DEPOSIT));
      assert.deepEqual(booking.status, { pending: {} });
    });

    it("rejects past service start", async () => {
      const owner = Keypair.generate();
      const { businessPda } = await createBusiness(owner);
      const customer = Keypair.generate();
      const now = Math.floor(Date.now() / 1000);
      try {
        await createBookingIntent({
          bookingId: randomBookingId(),
          business: businessPda,
          customer: customer.publicKey,
          depositAmount: DEFAULT_DEPOSIT,
          serviceStart: new anchor.BN(now - 3600),
          serviceEnd: new anchor.BN(now + 3600),
          payer: owner,
        });
        assert.fail("expected InvalidServiceStart");
      } catch (e: any) {
        assert.include(e.toString(), "InvalidServiceStart");
      }
    });

    it("rejects end-before-start window", async () => {
      const owner = Keypair.generate();
      const { businessPda } = await createBusiness(owner);
      const customer = Keypair.generate();
      const now = Math.floor(Date.now() / 1000);
      try {
        await createBookingIntent({
          bookingId: randomBookingId(),
          business: businessPda,
          customer: customer.publicKey,
          depositAmount: DEFAULT_DEPOSIT,
          serviceStart: new anchor.BN(now + 7200),
          serviceEnd: new anchor.BN(now + 3600),
          payer: owner,
        });
        assert.fail("expected InvalidServiceWindow");
      } catch (e: any) {
        assert.include(e.toString(), "InvalidServiceWindow");
      }
    });
  });

  // ─────────────────────────────────────────────────────────────
  //  3. lock_deposit
  // ─────────────────────────────────────────────────────────────
  describe("lock_deposit", () => {
    it("transfers USDC from customer to escrow and sets status=Confirmed", async () => {
      const owner = Keypair.generate();
      const { businessPda } = await createBusiness(owner);
      const { customer, customerAta } = await setupCustomerWithUsdc(100_000_000);

      const bookingId = randomBookingId();
      const now = Math.floor(Date.now() / 1000);
      await createBookingIntent({
        bookingId,
        business: businessPda,
        customer: customer.publicKey,
        depositAmount: DEFAULT_DEPOSIT,
        serviceStart: new anchor.BN(now + 3600),
        serviceEnd: new anchor.BN(now + 7200),
        payer: owner,
      });

      const { bookingPda, escrowAta } = await lockDeposit({ bookingId, customer, customerAta });

      const escrowAccount = await getAccount(provider.connection, escrowAta);
      assert.equal(escrowAccount.amount.toString(), DEFAULT_DEPOSIT.toString());

      const booking = await (program.account as any).booking.fetch(bookingPda);
      assert.deepEqual(booking.status, { confirmed: {} });
    });

    it("rejects wrong customer signer", async () => {
      const owner = Keypair.generate();
      const { businessPda } = await createBusiness(owner);
      const { customer, customerAta } = await setupCustomerWithUsdc(100_000_000);
      const imposter = Keypair.generate();
      await airdrop(imposter.publicKey, 2);

      const bookingId = randomBookingId();
      const now = Math.floor(Date.now() / 1000);
      await createBookingIntent({
        bookingId,
        business: businessPda,
        customer: customer.publicKey,
        depositAmount: DEFAULT_DEPOSIT,
        serviceStart: new anchor.BN(now + 3600),
        serviceEnd: new anchor.BN(now + 7200),
        payer: owner,
      });

      const [bookingPda] = deriveBookingPda(bookingId);
      const [escrowAuthority] = deriveEscrowAuthority(bookingId);
      const escrowAta = await createUsdcAta(escrowAuthority, true);
      const imposterAta = (
        await getOrCreateAssociatedTokenAccount(
          provider.connection,
          payerKp,
          usdcMint,
          imposter.publicKey
        )
      ).address;

      try {
        await program.methods
          .lockDeposit()
          .accounts({
            booking: bookingPda,
            customer: imposter.publicKey,
            customerTokenAccount: imposterAta,
            escrowTokenAccount: escrowAta,
            escrowAuthority,
            usdcMint,
            tokenProgram: TOKEN_PROGRAM_ID,
          })
          .signers([imposter])
          .rpc();
        assert.fail("expected UnauthorizedCustomer");
      } catch (e: any) {
        assert.include(e.toString(), "UnauthorizedCustomer");
      }
    });
  });

  // ─────────────────────────────────────────────────────────────
  //  4. confirm_attendance — full refund
  // ─────────────────────────────────────────────────────────────
  describe("confirm_attendance", () => {
    it("returns 100% to customer and sets status=Released", async () => {
      const owner = Keypair.generate();
      const { businessPda } = await createBusiness(owner);
      const { customer, customerAta } = await setupCustomerWithUsdc(100_000_000);

      const bookingId = randomBookingId();
      const now = Math.floor(Date.now() / 1000);
      await createBookingIntent({
        bookingId,
        business: businessPda,
        customer: customer.publicKey,
        depositAmount: DEFAULT_DEPOSIT,
        serviceStart: new anchor.BN(now + 3600),
        serviceEnd: new anchor.BN(now + 7200),
        payer: owner,
      });

      const { bookingPda, escrowAuthority, escrowAta } = await lockDeposit({
        bookingId,
        customer,
        customerAta,
      });

      const customerBefore = (await getAccount(provider.connection, customerAta)).amount;

      await program.methods
        .confirmAttendance()
        .accounts({
          booking: bookingPda,
          business: businessPda,
          businessOwner: owner.publicKey,
          customerTokenAccount: customerAta,
          escrowTokenAccount: escrowAta,
          escrowAuthority,
          usdcMint,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([owner])
        .rpc();

      const customerAfter = (await getAccount(provider.connection, customerAta)).amount;
      const escrowAfter = (await getAccount(provider.connection, escrowAta)).amount;
      assert.equal(escrowAfter.toString(), "0");
      assert.equal(
        (customerAfter - customerBefore).toString(),
        DEFAULT_DEPOSIT.toString()
      );

      const booking = await (program.account as any).booking.fetch(bookingPda);
      assert.deepEqual(booking.status, { released: {} });
    });
  });

  // ─────────────────────────────────────────────────────────────
  //  5. release_partial — 50/50
  // ─────────────────────────────────────────────────────────────
  describe("release_partial", () => {
    it("splits escrow 50/50 between customer and business", async () => {
      const owner = Keypair.generate();
      const { businessPda, ownerAta } = await createBusiness(owner);
      const { customer, customerAta } = await setupCustomerWithUsdc(100_000_000);

      const bookingId = randomBookingId();
      const now = Math.floor(Date.now() / 1000);
      await createBookingIntent({
        bookingId,
        business: businessPda,
        customer: customer.publicKey,
        depositAmount: DEFAULT_DEPOSIT,
        serviceStart: new anchor.BN(now + 3600),
        serviceEnd: new anchor.BN(now + 7200),
        payer: owner,
      });

      const { bookingPda, escrowAuthority, escrowAta } = await lockDeposit({
        bookingId,
        customer,
        customerAta,
      });

      const customerBefore = (await getAccount(provider.connection, customerAta)).amount;
      const ownerBefore = (await getAccount(provider.connection, ownerAta)).amount;

      // 5000 bps = 50% to customer
      await program.methods
        .releasePartial(5000)
        .accounts({
          booking: bookingPda,
          business: businessPda,
          businessOwner: owner.publicKey,
          customerTokenAccount: customerAta,
          businessTokenAccount: ownerAta,
          escrowTokenAccount: escrowAta,
          escrowAuthority,
          usdcMint,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([owner])
        .rpc();

      const customerAfter = (await getAccount(provider.connection, customerAta)).amount;
      const ownerAfter = (await getAccount(provider.connection, ownerAta)).amount;
      const half = DEFAULT_DEPOSIT.divn(2);

      assert.equal((customerAfter - customerBefore).toString(), half.toString());
      assert.equal((ownerAfter - ownerBefore).toString(), half.toString());

      const booking = await (program.account as any).booking.fetch(bookingPda);
      assert.deepEqual(booking.status, { partiallyReleased: {} });
    });

    it("rejects bps > 10000", async () => {
      const owner = Keypair.generate();
      const { businessPda, ownerAta } = await createBusiness(owner);
      const { customer, customerAta } = await setupCustomerWithUsdc(100_000_000);

      const bookingId = randomBookingId();
      const now = Math.floor(Date.now() / 1000);
      await createBookingIntent({
        bookingId,
        business: businessPda,
        customer: customer.publicKey,
        depositAmount: DEFAULT_DEPOSIT,
        serviceStart: new anchor.BN(now + 3600),
        serviceEnd: new anchor.BN(now + 7200),
        payer: owner,
      });
      const { bookingPda, escrowAuthority, escrowAta } = await lockDeposit({
        bookingId,
        customer,
        customerAta,
      });

      try {
        await program.methods
          .releasePartial(15000)
          .accounts({
            booking: bookingPda,
            business: businessPda,
            businessOwner: owner.publicKey,
            customerTokenAccount: customerAta,
            businessTokenAccount: ownerAta,
            escrowTokenAccount: escrowAta,
            escrowAuthority,
            usdcMint,
            tokenProgram: TOKEN_PROGRAM_ID,
          })
          .signers([owner])
          .rpc();
        assert.fail("expected InvalidCustomerShare");
      } catch (e: any) {
        assert.include(e.toString(), "InvalidCustomerShare");
      }
    });
  });

  // ─────────────────────────────────────────────────────────────
  //  6. claim_full — grace not elapsed (revert path tested)
  // ─────────────────────────────────────────────────────────────
  describe("claim_full", () => {
    it("rejects when service_end + 24h has not elapsed", async () => {
      const owner = Keypair.generate();
      const { businessPda, ownerAta } = await createBusiness(owner);
      const { customer, customerAta } = await setupCustomerWithUsdc(100_000_000);

      const bookingId = randomBookingId();
      const now = Math.floor(Date.now() / 1000);
      await createBookingIntent({
        bookingId,
        business: businessPda,
        customer: customer.publicKey,
        depositAmount: DEFAULT_DEPOSIT,
        serviceStart: new anchor.BN(now + 3600),
        serviceEnd: new anchor.BN(now + 7200),
        payer: owner,
      });
      const { bookingPda, escrowAuthority, escrowAta } = await lockDeposit({
        bookingId,
        customer,
        customerAta,
      });

      // Treasury just an arbitrary new wallet's ATA
      const treasury = Keypair.generate();
      await airdrop(treasury.publicKey, 1);
      const treasuryAta = (
        await getOrCreateAssociatedTokenAccount(
          provider.connection,
          payerKp,
          usdcMint,
          treasury.publicKey
        )
      ).address;

      try {
        await program.methods
          .claimFull()
          .accounts({
            booking: bookingPda,
            business: businessPda,
            businessOwner: owner.publicKey,
            businessTokenAccount: ownerAta,
            treasuryTokenAccount: treasuryAta,
            escrowTokenAccount: escrowAta,
            escrowAuthority,
            usdcMint,
            tokenProgram: TOKEN_PROGRAM_ID,
          })
          .signers([owner])
          .rpc();
        assert.fail("expected NoShowGraceNotElapsed");
      } catch (e: any) {
        assert.include(e.toString(), "NoShowGraceNotElapsed");
      }
    });

    it.skip("succeeds after grace — TODO migrate to bankrun for clock advance", async () => {
      // The Solana validator's real clock means we'd need to wait 24h+.
      // bankrun supports BanksClient.warpToSlot() / warpToTimestamp().
      // For the hackathon, the revert path above is sufficient evidence.
    });
  });

  // ─────────────────────────────────────────────────────────────
  //  7. customer_cancel
  // ─────────────────────────────────────────────────────────────
  describe("customer_cancel", () => {
    it("full refund when cancelling well before cancellation_hours", async () => {
      // cancellation_hours=1 (minimum), service in 2h → before threshold
      const owner = Keypair.generate();
      const { businessPda, ownerAta } = await createBusiness(owner, 1);
      const { customer, customerAta } = await setupCustomerWithUsdc(100_000_000);

      const bookingId = randomBookingId();
      const now = Math.floor(Date.now() / 1000);
      await createBookingIntent({
        bookingId,
        business: businessPda,
        customer: customer.publicKey,
        depositAmount: DEFAULT_DEPOSIT,
        serviceStart: new anchor.BN(now + 7200), // 2h ahead
        serviceEnd: new anchor.BN(now + 10800),
        payer: owner,
      });
      const { bookingPda, escrowAuthority, escrowAta } = await lockDeposit({
        bookingId,
        customer,
        customerAta,
      });

      const customerBefore = (await getAccount(provider.connection, customerAta)).amount;

      await program.methods
        .customerCancel()
        .accounts({
          booking: bookingPda,
          business: businessPda,
          customer: customer.publicKey,
          customerTokenAccount: customerAta,
          businessTokenAccount: ownerAta,
          escrowTokenAccount: escrowAta,
          escrowAuthority,
          usdcMint,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([customer])
        .rpc();

      const customerAfter = (await getAccount(provider.connection, customerAta)).amount;
      assert.equal(
        (customerAfter - customerBefore).toString(),
        DEFAULT_DEPOSIT.toString()
      );
      const booking = await (program.account as any).booking.fetch(bookingPda);
      assert.deepEqual(booking.status, { customerCancelled: {} });
    });

    it("50/50 split when cancelling within cancellation window", async () => {
      // cancellation_hours=24, service in 1h → past threshold (late cancel)
      const owner = Keypair.generate();
      const { businessPda, ownerAta } = await createBusiness(owner, 24);
      const { customer, customerAta } = await setupCustomerWithUsdc(100_000_000);

      const bookingId = randomBookingId();
      const now = Math.floor(Date.now() / 1000);
      await createBookingIntent({
        bookingId,
        business: businessPda,
        customer: customer.publicKey,
        depositAmount: DEFAULT_DEPOSIT,
        serviceStart: new anchor.BN(now + 3600), // 1h ahead, within 24h window
        serviceEnd: new anchor.BN(now + 7200),
        payer: owner,
      });
      const { bookingPda, escrowAuthority, escrowAta } = await lockDeposit({
        bookingId,
        customer,
        customerAta,
      });

      const customerBefore = (await getAccount(provider.connection, customerAta)).amount;
      const ownerBefore = (await getAccount(provider.connection, ownerAta)).amount;

      await program.methods
        .customerCancel()
        .accounts({
          booking: bookingPda,
          business: businessPda,
          customer: customer.publicKey,
          customerTokenAccount: customerAta,
          businessTokenAccount: ownerAta,
          escrowTokenAccount: escrowAta,
          escrowAuthority,
          usdcMint,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([customer])
        .rpc();

      const customerAfter = (await getAccount(provider.connection, customerAta)).amount;
      const ownerAfter = (await getAccount(provider.connection, ownerAta)).amount;
      const half = DEFAULT_DEPOSIT.divn(2);
      assert.equal((customerAfter - customerBefore).toString(), half.toString());
      assert.equal((ownerAfter - ownerBefore).toString(), half.toString());
      const booking = await (program.account as any).booking.fetch(bookingPda);
      assert.deepEqual(booking.status, { lateCancelled: {} });
    });
  });
});
