"""
Solana client — anchorpy wrapper for the VoiceDesk program.

Provides:
  - lazy program instance loaded from IDL
  - PDA derivation helpers (business / booking / escrow authority)
  - dispatcher functions called by main.py when ElevenLabs invokes a tool

The IDL is generated by `anchor build` into target/idl/voicedesk.json.
Set IDL_PATH env var to override the location for containerised runs.
"""

from __future__ import annotations

import json
import logging
import os
import secrets
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from anchorpy import Context, Idl, Program, Provider, Wallet
from solana.rpc.async_api import AsyncClient
from solders.keypair import Keypair
from solders.pubkey import Pubkey
from solders.system_program import ID as SYS_PROGRAM_ID

log = logging.getLogger("voicedesk.solana")

# ─────────────────────────────────────────────────────────────────
#  Configuration (read from env)
# ─────────────────────────────────────────────────────────────────

RPC_URL = os.getenv("SOLANA_RPC_URL", "https://api.devnet.solana.com")
PROGRAM_ID_STR = os.getenv("ANCHOR_PROGRAM_ID", "")
WALLET_PATH = os.getenv("ANCHOR_WALLET", "./keys/bridge-wallet.json")
USDC_MINT_STR = os.getenv("USDC_MINT", "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU")

IDL_PATH = Path(
    os.getenv("IDL_PATH", str(Path(__file__).parent.parent / "target" / "idl" / "voicedesk.json"))
)

# Seed prefixes — must match Rust code
BUSINESS_SEED = b"business"
BOOKING_SEED = b"booking"
ESCROW_SEED = b"escrow"


# ─────────────────────────────────────────────────────────────────
#  Lazy program loader
# ─────────────────────────────────────────────────────────────────

_program: Program | None = None
_client: AsyncClient | None = None


def _load_wallet() -> Keypair:
    path = Path(WALLET_PATH).expanduser().resolve()
    if not path.exists():
        raise FileNotFoundError(
            f"Bridge wallet not found at {path}. "
            f"Generate one with `solana-keygen new -o {path}`."
        )
    raw = json.loads(path.read_text())
    return Keypair.from_bytes(bytes(raw))


async def get_program() -> Program:
    """Return a cached anchorpy Program instance (loads IDL on first call)."""
    global _program, _client

    if _program is not None:
        return _program

    if not IDL_PATH.exists():
        raise FileNotFoundError(
            f"IDL not found at {IDL_PATH}. Run `anchor build` first."
        )
    if not PROGRAM_ID_STR:
        raise RuntimeError(
            "ANCHOR_PROGRAM_ID env var not set. "
            "After deploy: `solana address -k target/deploy/voicedesk-keypair.json`"
        )

    _client = AsyncClient(RPC_URL)
    wallet = Wallet(_load_wallet())
    provider = Provider(_client, wallet)

    idl = Idl.from_json(IDL_PATH.read_text())
    program_id = Pubkey.from_string(PROGRAM_ID_STR)
    _program = Program(idl, program_id, provider)
    log.info("Anchor program loaded: %s", program_id)
    return _program


# ─────────────────────────────────────────────────────────────────
#  PDA derivation
# ─────────────────────────────────────────────────────────────────


def derive_business_pda(owner: Pubkey, program_id: Pubkey) -> tuple[Pubkey, int]:
    return Pubkey.find_program_address([BUSINESS_SEED, bytes(owner)], program_id)


def derive_booking_pda(booking_id: bytes, program_id: Pubkey) -> tuple[Pubkey, int]:
    if len(booking_id) != 32:
        raise ValueError(f"booking_id must be 32 bytes, got {len(booking_id)}")
    return Pubkey.find_program_address([BOOKING_SEED, booking_id], program_id)


def derive_escrow_authority(booking_id: bytes, program_id: Pubkey) -> tuple[Pubkey, int]:
    if len(booking_id) != 32:
        raise ValueError(f"booking_id must be 32 bytes, got {len(booking_id)}")
    return Pubkey.find_program_address([ESCROW_SEED, booking_id], program_id)


def random_booking_id() -> bytes:
    """32-byte cryptographically random booking ID."""
    return secrets.token_bytes(32)


# ─────────────────────────────────────────────────────────────────
#  Read tools
# ─────────────────────────────────────────────────────────────────


async def check_availability(business_pubkey: str, **_: Any) -> dict[str, Any]:
    """Fetch a Business PDA from chain and return its config."""
    program = await get_program()
    pubkey = Pubkey.from_string(business_pubkey)
    business = await program.account["Business"].fetch(pubkey)
    return {
        "name": business.name,
        "vertical": str(business.vertical).split(".")[-1],
        "default_deposit": int(business.default_deposit_amount),
        "cancellation_hours": int(business.cancellation_hours),
    }


async def get_booking_status(booking_id_hex: str) -> dict[str, Any]:
    """Read a Booking PDA to surface current lifecycle state to the agent."""
    program = await get_program()
    booking_id = bytes.fromhex(booking_id_hex)
    booking_pda, _ = derive_booking_pda(booking_id, program.program_id)
    booking = await program.account["Booking"].fetch(booking_pda)
    return {
        "booking_id": booking_id_hex,
        "status": str(booking.status).split(".")[-1],
        "deposit_amount": int(booking.deposit_amount),
        "service_start": int(booking.service_start),
        "service_end": int(booking.service_end),
        "customer": str(booking.customer),
        "business": str(booking.business),
    }


# ─────────────────────────────────────────────────────────────────
#  Write tools
# ─────────────────────────────────────────────────────────────────


@dataclass
class BookingIntentResult:
    booking_id_hex: str
    booking_pda: str
    escrow_authority: str
    deposit_amount: int
    service_start: int
    service_end: int
    payment_url: str
    tx_signature: str


async def create_booking_intent(
    business_pubkey: str,
    customer_pubkey: str,
    deposit_amount: int,
    service_start: int,
    service_end: int,
) -> BookingIntentResult:
    """
    Build and submit a `create_booking_intent` instruction.
    Bridge wallet is the payer. Customer does NOT need to sign here —
    they sign `lock_deposit` later from the public payment page.
    """
    program = await get_program()
    business = Pubkey.from_string(business_pubkey)
    customer = Pubkey.from_string(customer_pubkey)
    booking_id = random_booking_id()

    booking_pda, _ = derive_booking_pda(booking_id, program.program_id)
    escrow_authority, _ = derive_escrow_authority(booking_id, program.program_id)
    payer = program.provider.wallet.public_key

    tx_sig = await program.rpc["create_booking_intent"](
        list(booking_id),
        deposit_amount,
        service_start,
        service_end,
        ctx=Context(
            accounts={
                "booking": booking_pda,
                "business": business,
                "customer": customer,
                "payer": payer,
                "system_program": SYS_PROGRAM_ID,
            },
        ),
    )
    log.info("create_booking_intent tx: %s", tx_sig)

    public_api = os.getenv("PUBLIC_API_URL", "http://localhost:3000")
    payment_url = f"{public_api}/pay/{booking_id.hex()}"

    return BookingIntentResult(
        booking_id_hex=booking_id.hex(),
        booking_pda=str(booking_pda),
        escrow_authority=str(escrow_authority),
        deposit_amount=deposit_amount,
        service_start=service_start,
        service_end=service_end,
        payment_url=payment_url,
        tx_signature=str(tx_sig),
    )


# ─────────────────────────────────────────────────────────────────
#  Health
# ─────────────────────────────────────────────────────────────────


def health_check() -> dict[str, Any]:
    return {
        "rpc_url": RPC_URL,
        "program_id": PROGRAM_ID_STR or "(not deployed yet)",
        "idl_exists": IDL_PATH.exists(),
        "idl_path": str(IDL_PATH),
        "wallet_path": str(Path(WALLET_PATH).expanduser()),
        "usdc_mint": USDC_MINT_STR,
    }
