use anchor_lang::prelude::*;

/// Lifecycle of a single booking.
///
/// State transitions:
///   Pending           → Confirmed         (lock_deposit)
///   Pending           → Expired           (timeout — Phase 2)
///   Confirmed         → Released          (confirm_attendance)
///   Confirmed         → PartiallyReleased (release_partial)
///   Confirmed         → Claimed           (claim_full, after grace)
///   Confirmed         → CustomerCancelled (customer_cancel, >cancellation_hours before)
///   Confirmed         → LateCancelled     (customer_cancel, <cancellation_hours before)
///   Confirmed         → Disputed          (raise_dispute — Phase 2)
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy, Default, PartialEq, Eq, Debug)]
pub enum BookingStatus {
    #[default]
    Pending,
    Confirmed,
    Released,
    PartiallyReleased,
    Claimed,
    CustomerCancelled,
    LateCancelled,
    Disputed,
}

/// A Booking represents a single customer reservation against a Business.
///
/// PDA seeds: ["booking", booking_id]
/// `booking_id` is a 32-byte client-generated identifier (e.g. UUID v4 → bytes,
/// or hash of business+customer+timestamp). It must be unique across the program.
#[account]
pub struct Booking {
    /// Unique booking identifier (32 bytes, generated by the bridge)
    pub booking_id: [u8; 32],
    /// The Business PDA this booking belongs to
    pub business: Pubkey,
    /// The customer's wallet (signs lock_deposit, customer_cancel)
    pub customer: Pubkey,
    /// Deposit amount in USDC base units (6 decimals)
    pub deposit_amount: u64,
    /// Service start (unix seconds)
    pub service_start: i64,
    /// Service end (unix seconds)
    pub service_end: i64,
    /// Current lifecycle state
    pub status: BookingStatus,
    /// When this booking record was created
    pub created_at: i64,
    /// PDA bump
    pub bump: u8,
}

impl Booking {
    /// Account size in bytes.
    /// Discriminator (8) + booking_id (32) + business (32) + customer (32)
    /// + deposit (8) + start (8) + end (8) + status (1) + created_at (8)
    /// + bump (1) = 138
    pub const SPACE: usize = 8 + 32 + 32 + 32 + 8 + 8 + 8 + 1 + 8 + 1;

    pub const SEED_PREFIX: &'static [u8] = b"booking";

    /// Seed prefix for the per-booking escrow token account authority PDA.
    /// Full seeds: ["escrow", booking_id]
    pub const ESCROW_SEED_PREFIX: &'static [u8] = b"escrow";

    /// Grace period after `service_end` before SMB can claim full deposit.
    /// 24 hours.
    pub const NO_SHOW_GRACE_SECONDS: i64 = 24 * 60 * 60;

    /// Protocol fee in basis points (5%) on no-show forfeits.
    pub const PROTOCOL_FEE_BPS: u16 = 500;

    /// Basis points denominator (100% = 10000).
    pub const BPS_DENOMINATOR: u64 = 10_000;

    /// True if the booking is in a finalized state (no further transitions possible).
    pub fn is_finalized(&self) -> bool {
        matches!(
            self.status,
            BookingStatus::Released
                | BookingStatus::PartiallyReleased
                | BookingStatus::Claimed
                | BookingStatus::CustomerCancelled
                | BookingStatus::LateCancelled
        )
    }
}
